[theme]
name = "Penumbra Light"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

[theme.base]
red = "#CA736C"
orange = "#BA823A"
yellow = "#8D9741"
green = "#47A477"
cyan = "#00A2AF"
blue = "#5794D0"
purple = "#9481CC"
magenta = "#BC73A4"
white = "#FFFDFB"
black = "#24272B"
grey = "#3E4044"



    # Shade- “white”, text in highlighted sections, emphasised borders
    # Shade selections, light borders, strongly emphasised content
    # Shade+ optional
    # Sky- emphasized content and emphasised UI text
    # Sky foreground, code, main content colour, text both in editors and UI elements
    # Sky+ comments, deemphasised content
    # Sun- foreground UI elements, rulers, indentation guides and similar
    # Sun main background colour
    # Sun+ “black”, deemphasized/receded background elements, selections, dark UI elements


[theme.syntax]
"comment" = "#9699a3"
"boolean" = "#965027"
"constant" = "#965027"
"type" = "$green"
"typeAlias" = "$green"
"number" = "#965027"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "$yellow"

"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"

"keyword" = "$magneta"
"selfKeyword" = "$magneta"

"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"
"variable.other.member" = "$red"

"string" = "#485e30"

"type.builtin" = "$cyan"
"builtinType" = "$cyan"
"escape" = "$cyan"
"embedded" = "$cyan"

[theme.ui]
"lapce.active_tab" = "$white"
"lapce.inactive_tab" = "$grey"
"lapce.error" = "$red"
"lapce.warn" = "#E9A700"
"lapce.dropdown_shadow" = "#cecacd"
"lapce.border" = "#cecacd"
"lapce.scroll_bar" = "#cecacd"

"terminal.cursor" = "#cecacd"
"terminal.foreground" = "$white"
"terminal.background" = "#d5d6db"
"terminal.white" = "$white"
"terminal.black" = "$grey"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "$white"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "$black"

"editor.background" = "#FFF7ED"
"editor.foreground" = "$white"
"editor.dim" = "#A0A1A7"
"editor.focus" = "#000000"
"editor.caret" = "#526FFF"
"editor.selection" = "$grey"
"editor.current_line" = "#F2F2F2"
"editor.link" = "$cyan"

"inlay_hint.foreground" = "$black"
"inlay_hint.background" = "#cecacd88"

"error_lens.error.foreground" = "$red"
"error_lens.error.background" = "#E4564920"
"error_lens.warning.foreground" = "$yellow"
"error_lens.warning.background" = "#C1840120"
"error_lens.other.foreground" = "#A0A1A7"
"error_lens.other.background" = "#A0A1A720"

"source_control.added" = "#50A14F32"
"source_control.removed" = "#FF526632"
"source_control.modified" = "#0184BC32"

"palette.background" = "#d5d6db"
"palette.current" = "#DBDBDC"

"completion.background" = "#d5d6db"
"completion.current" = "#DBDBDC"

"hover.background" = "#d5d6db"

"activity.background" = "#d5d6db"
"activity.current" = "$white"

"panel.background" = "#d5d6db"
"panel.current" = "#DBDBDC"
"panel.hovered" = "#E4E4E6"

"status.background" = "#d5d6db"
"status.modal.normal" = "$blue"
"status.modal.insert" = "$red"
"status.modal.visual" = "$yellow"
"status.modal.terminal" = "$purple"

"markdown.blockquote" = "#f4ede8"